### ISSUE TITLE
Incorrect issues list

### ISSUE THREAD

**Issue by lzhabo** [camden-smallwood/sway-analyzer#3]
1) List of unused imports, but they are used in calls , like this 
```
let clearing_house_contract = abi(ClearingHouseContract, CLEARING_HOUSE_ADDRESS);
```
 L10: Found unused import: `ClearingHouseContract`. Consider removing any unused imports.
        L11: Found unused import: `AccountBalanceContract`. Consider removing any unused imports.
        L12: Found unused import: `PerpMarketContract`. Consider removing any unused imports.
        L13: Found unused import: `VaultContract`. Consider removing any unused imports.

2) List of storage variables without access restriction, but they have this access, for example
```
 #[payable, storage(read, write)]
    fn deposit_collateral(){
```
3) Can't run analyzer in folders where I have mode files in src, not only main.sw
Error: LineNotFound("src/main.sw", 18117)
<img width="439" alt="image" src="https://github.com/camden-smallwood/sway-analyzer/assets/52199564/395bc86a-cc07-4bbd-ba53-7835cfbdc6dd">
<img width="217" alt="image" src="https://github.com/camden-smallwood/sway-analyzer/assets/52199564/5c2ee179-b31c-45bb-bc2c-b987efb68835">

**Comment by camden-smallwood** [comment]
1. Thanks for pointing this out, this should be fixed as of commit [c32926576dd685f794806631dd5ee26c521f8942](https://github.com/camden-smallwood/sway-analyzer/commit/c32926576dd685f794806631dd5ee26c521f8942), which has been released as version `0.1.7`.

2. Access restriction is referring to the execution context, meaning there is no check against the transaction sender (`msg_sender()`) inside that function, which allows anyone to make changes to the storage variable(s). If that's your intended use case for the function, then you can ignore that finding. It's better to have a false positive than to not point it out.

3. I'm not sure I understand what's happening here, could you elaborate?
